module.exports = {
  config: {
    name: "sad",
    aliases: ["depressed"],
    version: "1.0",
    author: "kshitiz",
    countDown: 20,
    role: 0,
    shortDescription: "",
    longDescription: "get video to increase your sadness",
    category: "fun",
    guide: "{p}{n}",
  },

  sentVideos: [],

  onStart: async function ({ api, event, message }) {
    const senderID = event.senderID;

    const loadingMessage = await message.reply({
      body: "loading video...\n to increase your sadness🤡!",
    });

    const link = [
      "https://drive.google.com/uc?export=download&id=1ztNdRo3Wsb5apAK5Nk7qCb5vnTzGooyT",
      "https://drive.google.com/uc?export=download&id=1zkWup1pVPuIvxsuBTNVATTfbscOjmqLx",
      "https://drive.google.com/uc?export=download&id=1zbxLB07ubkzBsJzLOjLnfehPxxwx0Ec3",
      "https://drive.google.com/uc?export=download&id=1zbm-0eIBlZq6QwgKilyLtFqc4NJQklKE",
      "https://drive.google.com/uc?export=download&id=1zIpvNFs998cvNxJCIO5D3PGE8fC-QkLc",
      "https://drive.google.com/uc?export=download&id=1z3fKb3i0FoUbsLZNvTNsQFZDTwy-U-xO",
      "https://drive.google.com/uc?export=download&id=1y6GWa_YvRc3W7huF-7pXCAXrgL5CVWvm",
      "https://drive.google.com/uc?export=download&id=1xqAZVB_9N9ebXD0Yq8owmHCU3kGUOvgW",
      "https://drive.google.com/uc?export=download&id=1xG7RwHxsq1cQLLL8sOoOLcmt3dYH3-2y",
      "https://drive.google.com/uc?export=download&id=1vjSftyqEqU1MT4J35Zs8I9U7odlmDS1i",
      "https://drive.google.com/uc?export=download&id=1vZ7OqlSf_MPp-AGZhIASyfn2GYdbZQQB",
      "https://drive.google.com/uc?export=download&id=1vOW1q5JMKkSV1noK5uu_AVxPZ3AZUlcj",
      "https://drive.google.com/uc?export=download&id=1v5thEILszoNaBdd-rFvfh4n5Okczkmr3",
      "https://drive.google.com/uc?export=download&id=1ulwoVYleuWqdqIvNk6IRkN9yMM73oiQQ",
      "https://drive.google.com/uc?export=download&id=1uVIExxswG2I5rEE2Pv-zH0t12sTWLPQ2",
      "https://drive.google.com/uc?export=download&id=1uCN2x1xIz5O5j37_nTzEqeCJD5_Qz_oa",
      "https://drive.google.com/uc?export=download&id=1tcrVXObD6Ctht-y9wFgfEJhZ5dscWiCb",
      "https://drive.google.com/uc?export=download&id=1rU40wX3aN86lsdtr3aGCAXmx5SYH0cxz",
      "https://drive.google.com/uc?export=download&id=1rK6dE-OE4BIXIlf-WC6hK91azTBSx62z",
      "https://drive.google.com/uc?export=download&id=1r2ClspyQkSGP2RKRg4oE-DmpGNOVDyzU",
      "https://drive.google.com/uc?export=download&id=1qwWqk1-w0unIxUehDtmgse2B013RAwRH",
      "https://drive.google.com/uc?export=download&id=1qqKEw74x5uSeMhyfQQMPI9fXSumffsar",
      "https://drive.google.com/uc?export=download&id=1q8IG-NGNA--6-UkYJsqrVgoR7Aag2709",
      "https://drive.google.com/uc?export=download&id=1pzvCEDmE4_JV86UbM4uYNTmFr-DFtiCi",
      "https://drive.google.com/uc?export=download&id=1pqZAjd0WJxNeMmxcjT0TTj9jUAE3TEbx",
      "https://drive.google.com/uc?export=download&id=1p_qI4J4hKneNrtkGdsNCSY-RTOxf-AG3",
      "https://drive.google.com/uc?export=download&id=1oYwGmqPsW6RSTf6h_MO6I4OnQIB07eCq",
      "https://drive.google.com/uc?export=download&id=1oX7wBYmEtRetmoJrFyFbqzfQ3O8aPMr8",
      "https://drive.google.com/uc?export=download&id=1nfMRrsU0-G-CcjGtEMGY-a0LbjjJYCj-",
      "https://drive.google.com/uc?export=download&id=1nK4h-TGxCF2bnlq9Vig7kRn69tP5tpmY",
      "https://drive.google.com/uc?export=download&id=1n6aZNlcWBNxXJLNp7o5g0SxnJupvxG9h",
      "https://drive.google.com/uc?export=download&id=1mR48-3LBW5BEXRWT7KAOczaCLKj3DAnq",
      "https://drive.google.com/uc?export=download&id=1mKDEeu4oIxgNogBcHRmDweEOpHbgszVm",
      "https://drive.google.com/uc?export=download&id=1m1NXxPpJDCoPdGaylakCsrT_j2b911t9",
      "https://drive.google.com/uc?export=download&id=1lvTc7nkJSwv5vkhCepiNTnJ4qOgNbv6q",
      "https://drive.google.com/uc?export=download&id=1llKrr7IqL_HgCOicIcQxwdJj9new8Smh",
      "https://drive.google.com/uc?export=download&id=1k3kxgrt4sVNuyX9Pifx_QSe-hvqHJYgw",
      "https://drive.google.com/uc?export=download&id=1jkq3WoQdxuMiRVnA8-srjvKsbovc94Im",
      "https://drive.google.com/uc?export=download&id=1jk8l2rpDdzRQx59a3OM2HTs4bkBEF6zZ",
      "https://drive.google.com/uc?export=download&id=1j_sXWNsBgAqHqHXUGSs-hAfGP8iEeLpK",
      "https://drive.google.com/uc?export=download&id=1jUyZEbhc3CqByh1-YUuDusoKt-JUVrTm",
      "https://drive.google.com/uc?export=download&id=1jHtxtQx0Zt8pA_ckkMdFZxBuyVYTLSue",
      "https://drive.google.com/uc?export=download&id=1imVLcSyU13pIMsLVWxo61HPrvzedP7Bg",
      "https://drive.google.com/uc?export=download&id=1ihD_sGR-0dKEYMbexkuXRZUz33Az1-wh",
      "https://drive.google.com/uc?export=download&id=1iHFjAtRcQou5LmU-cZO-Hl_YUkxjjYrB",
      "https://drive.google.com/uc?export=download&id=1hjNQFU39K4ddslSducGukMcDcstRzPv4",
      "https://drive.google.com/uc?export=download&id=1hgeKXyWzmCXZgWImzm5CmRqqd4RPSRXZ",
      "https://drive.google.com/uc?export=download&id=1hUw8czFaie0vPKxbte_C0yMAyRTe__9l",
      "https://drive.google.com/uc?export=download&id=1hNzZ9PnEB7RjSB1T0fj_aiUT2TtB_gbQ",
      "https://drive.google.com/uc?e
